image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - mkdir public/documentation
    - cp -rp Documentation public/documenation
  artifacts:
    paths:
      - public
  only:
    - master
